<?php

/**
 * Implements hook_form_alter().
 */
function webform_multiplefields_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "webform_component_edit_form"){
    formSetComponentsSettings($form);
  }
  if(isSet($form['#node']->nid) && ("webform_client_form_{$form['#node']->nid}" == $form_id)){

    setComponentsMultiples($form['#node']->nid, $form['#node']->webform['components'], $form);
    $form['#validate'][0] = 'webformMultiplefieldsClientFormValidate';
    $form['#validate'][1] = '_webform_client_form_validate';
  }

}


/**
 * Implements hook_webform_component_insert().
 */
function webform_multiplefields_webform_component_insert($component) {
  saveSettingsComponent($component);
}

/**
 * Implements hook_webform_component_presave().
 */
function webform_multiplefields_webform_component_presave(&$component) {
  saveSettingsComponent($component);
}

/**
 * Implements hook_webform_component_delete().
 */
function webform_multiplefields_webform_component_delete($component) {
  deleteSettingsComponent($component);
}

/**
 * Set settings to field
 */
function formSetComponentsSettings(&$form) {
  $settings_component = loadSettingsComponent($form['nid']['#value'], $form['cid']['#value']);
  $form['webform_multiplefields'] = array(
    '#type' => 'fieldset',
    '#title' => t('Field Value Settings'),
    '#weight' => 5,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['webform_multiplefields']['cardinality'] = array(
    '#type' => 'select',
    '#title' => t('Number of values'),
    '#default_value' => (isSet($settings_component->cardinality)? $settings_component->cardinality : 1 ),
    '#options' => getOptionsCardinality(),
  );
}

/**
 * Get settings of component, by the nid, cid and type. If not been set in db, return settings default.
 */
function loadSettingsComponent($nid, $cid) {
  $component_settings = db_select('webform_multiplefields', 'wm')
    ->fields('wm')
    ->condition('nid', $nid)
    ->condition('cid', $cid)
    ->execute()
    ->fetchObject();
  return $component_settings;
}

/**
 * Create settings the field multiple.
 */
function createSettingsComponent($component) {
  $component['cid'] = !empty($component['cid'])? $component['cid'] : getNextIdComponent($component['nid']);
  $wmid = db_insert('webform_multiplefields')->fields(array(
    'nid' => $component['nid'],
    'cid' => $component['cid'],
    'cardinality' => $component['webform_multiplefields']['cardinality'],
    'form_key' => $component['form_key'],
  ))->execute();
  return $wmid;
}

/**
 * Save or update settings of component.
 */
function saveSettingsComponent($component) {
  if(!isSet($component['webform_multiplefields']['cardinality'])){
    return false;
  }
  $component_exists = loadSettingsComponent($component['nid'], $component['cid']);
  if(empty($component_exists)){
    createSettingsComponent($component);
  } else {
    updateSettingsComponent($component);
  }
  return false;
}

/**
 * Update settings the field multiple.
 */
function updateSettingsComponent($component) {
  $wmid = db_update('webform_multiplefields')->fields(array(
    'nid' => $component['nid'],
    'cid' => $component['cid'],
    'cardinality' => $component['webform_multiplefields']['cardinality'],
    'form_key' => $component['form_key'],
  ))->condition('nid', $component['nid'], '=')->condition('cid', $component['cid'], '=')->execute();
  return $wmid;

}

/**
 * Delete settings the field multiple.
 */
function deleteSettingsComponent($component) {
  db_delete('webform_multiplefields')
  ->condition('nid', $component['nid'])
  ->condition('cid', $component['cid'])
  ->execute();
}


function setTitleElements(&$elements){
  if(!isSet($elements['submitted'])){
    return $elements;
  }

  foreach($elements['submitted'] as $key => $component){
    if(!isSet($component[0]) || !is_array($component[0])){
      continue;
    }

    foreach($component as $key_index => $item){
      if(!isset($item['#webform_component'])){
        continue;
      }
      $elements['submitted'][$key][$key_index]['#title'] = $item['#webform_component']['name'];
    }
  }
  return $elements;
}


function buttonAddMore(&$form){
  $form['button_add_more'] = array(
    '#type' => 'button',
    '#value' => t("Add More"),
    '#ajax' => array(
      'callback' => "buttonAddMoreField",
      'wrapper' => "button_add_more_field",
        'method' => 'replace',
    ),
  );
}

function addFieldsetToFieldsMultiples(&$form, $key){
  $form[$key] = array(
    '#type' => 'fieldset',
    '#title' => $form[$key]['#title'],
    '#weight' => 5,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
}

function buttonAddMoreField($form, &$form_state){
  print_r("ok");die;
}

/**
 * Return options of cardinality.
 */
function getOptionsCardinality($start = 1, $end = 10){
  $range = drupal_map_assoc(range($start, $end));
  return array(FIELD_CARDINALITY_UNLIMITED => t('Unlimited')) + $range;
}

/**
 * Return id of the next component.
 */
function getNextIdComponent($nid){
  $next_id_query = db_select('webform_component')->condition('nid', $nid);
  $next_id_query->addExpression('MAX(cid) + 1', 'cid');
  return $next_id_query->execute()->fetchField();
}

function setComponentsMultiples($nid, $components, &$form){
  $new_form = array();
  foreach($components as $component){
    $cpSettings = loadSettingsComponent($nid, $component['cid']);
    if(is_numeric($cpSettings->form_key)){
      continue;
    }
    $new_form = array_merge($form['submitted'], setMultipleComponentRecursive($form['submitted'], $cpSettings->form_key, $cpSettings));
  }
  return $new_form;
}

/**
 * Ainda vou melhorar essa poha
 */
function setMultipleComponentRecursive(&$form, $key, $cpSettings, $cpUnlimited = FALSE){
  if (!is_array($form[$key])) {
    return $form;
  }

  $cpMultiples = array();
  if($cpSettings->cardinality < 0){
    $cpUnlimited = TRUE;
    $item = $form[$key];

    addFieldsetToFieldsMultiples($form[$key], $key);

    $cpSettings->cardinality = 1;
    $form[$key] = $item;
  }

  for($index = 0; $index < $cpSettings->cardinality; $index++){
    if(isAdminSubmission())  {
      $cpDefautValueSettings = array(
        'nid' => $cpSettings->nid,
        'cid' => $cpSettings->cid,
        'sid' => adminSubmissionGetSid(),
        'no' => $index,
      );

      setDefaultValueComponent($form[$key], $cpDefautValueSettings);
    }

    $form[$key]['#weight'] = $index;

    unsetTitleComponent($form[$key], $index);

    $cpMultiples[]  = $form[$key];
  }

  $form[$key] = $cpMultiples;
  if($cpUnlimited){
    buttonAddMore($form[$key]);
  }

  foreach ($form as &$subarray){
    setMultipleComponentRecursive($subarray, $key, $component_settings);
  }

  return $form;
}


function getDefaultValueByNidCidSidNo($settings){
  $component_value = db_select('webform_submitted_data', 'wsd')
    ->fields('wsd', array('data'))
    ->condition('nid', $settings['nid'])
    ->condition('cid', $settings['cid'])
    ->condition('sid', $settings['sid'])
    ->condition('no', $settings['no'])
    ->execute()
    ->fetchField();
  return $component_value;
}


function setDefaultValueComponent(&$component, $settings){
  $settings_value = array(
    'nid' => $settings['nid'],
    'cid' => $settings['cid'],
    'sid' => $settings['sid'],
    'no' => $settings['no'],
  );
  $component['#default_value'] = getDefaultValueByNidCidSidNo($settings_value);
  return $component;
}


/**
 * Verify if page admin submission.
 */
function isAdminSubmission(){
  $args = arg();
  if( (isSet($args[2]) && ($args[2] == "submission")) && (isSet($args[4]) && ($args[4] == "edit")) ){
    return TRUE;
  }
  return FALSE;
}

/**
 * Verify if page admin submission.
 */
function adminSubmissionGetSid(){
  $args = arg();
  if(!isSet($args[3])){
    return FALSE;
  }
  return $args[3];
}

function webformMultiplefieldsClientFormValidate($elements, &$form_state, $first_run = TRUE) {
  $elements['complete form']['submitted'] = setTitleElements($form_state['complete form']);
}

/**
 * Unset title if <> 0
 */
function unsetTitleComponent(&$form, $index){
  if($index <> 0){
    unset($form['#title']);
  }
}